import { normalizeSymbol } from "./normalization";
import type { AdapterAccountContext, AdapterCommandContext, AdapterHealthSnapshot, AdapterOrderResult, AdapterOrderSnapshot, AdapterPositionSnapshot, AdapterProtectionSnapshot, CryptoAdapter, CryptoEnvironment, CryptoExchangeClient, FatalError as FatalErrorType, VerificationStatus } from "./types";
import { FatalError, RetryableError } from "./types";

export function assertContext(ctx: AdapterAccountContext): void { if (!ctx.customerId || !ctx.accountId || !ctx.executorId) throw new FatalError("customerId/accountId/executorId are required", "missing_account_context"); if (!isEnvironment(ctx.environment)) throw new FatalError("explicit crypto environment is required", "invalid_environment"); if (ctx.environment === "live" && ctx.baseUrl && /testnet|demo/i.test(ctx.baseUrl)) throw new FatalError("live execution cannot use demo/testnet endpoint", "invalid_environment"); }
export function isEnvironment(v: unknown): v is CryptoEnvironment { return v === "demo" || v === "testnet" || v === "live"; }
export function classifyExchangeError(error: unknown): FatalErrorType | RetryableError { if (error instanceof RetryableError || error instanceof FatalError) return error; const msg = error instanceof Error ? error.message : String(error); if (/timeout|network|rate|429|temporar/i.test(msg)) return new RetryableError(msg, "retryable_exchange_error"); if (/auth|signature|key/i.test(msg)) return new FatalError(msg, "auth_failure"); if (/symbol/i.test(msg)) return new FatalError(msg, "invalid_symbol"); if (/balance|margin/i.test(msg)) return new FatalError(msg, "insufficient_balance"); if (/reject|filter|minimum/i.test(msg)) return new FatalError(msg, "order_rejected"); if (/environment/i.test(msg)) return new FatalError(msg, "invalid_environment"); return new FatalError(msg, "exchange_error"); }

export abstract class BaseCryptoAdapter implements CryptoAdapter {
  protected connected = false; protected readonly accepted = new Map<string, AdapterOrderResult>();
  protected constructor(protected readonly exchange: "binance" | "bybit", protected readonly account: AdapterAccountContext, protected readonly client: CryptoExchangeClient) { assertContext(account); }
  async connect() { await this.client.connect(); this.connected = true; return this.health(); }
  async disconnect() { await this.client.disconnect(); this.connected = false; return this.health(); }
  async health(): Promise<AdapterHealthSnapshot> { return { status: this.connected ? "connected" : "disconnected", exchange: this.exchange, environment: this.account.environment, connected: this.connected, account: this.account, checkedAt: new Date().toISOString(), reasonCodes: this.connected ? [] : ["not_connected"] }; }
  async heartbeat() { const ok = await this.client.ping(); this.connected = ok; return this.health(); }
  async reconnect() { await this.disconnect(); return this.connect(); }
  getPosition(symbol: string) { return this.client.getPosition(normalizeSymbol(symbol)); } getOrders(symbol?: string) { return this.client.getOrders(symbol ? normalizeSymbol(symbol) : undefined); } getBalance() { return this.client.getBalance(); } getSymbolInfo(symbol: string) { return this.client.getSymbolInfo(normalizeSymbol(symbol)); }
  async synchronize() { const [positions, orders] = await Promise.all([this.client.getPositions(), this.client.getOrders()]); return { positions, orders, protection: protectionFromOrders(orders) }; }
  async repair(): Promise<AdapterOrderResult> { const sync = await this.synchronize(); return this.result({ commandId: "repair", idempotencyKey: "repair", ...this.account }, false, undefined, sync.positions[0], sync.orders, sync.positions, sync.protection, "UNKNOWN", ["manual_repair_snapshot_only"]); }
  async openPosition(ctx: AdapterCommandContext, req: any) { const symbol = normalizeSymbol(req.symbol); const side = req.side === "LONG" ? "BUY" : "SELL"; const result = await this.execute(ctx, async () => this.client.placeOrder({ symbol, side, quantity: req.quantity, type: req.orderType ?? "MARKET", price: req.price, clientOrderId: ctx.idempotencyKey }), symbol, { quantity: req.quantity, entryPrice: req.price, stopLoss: req.stopLoss, takeProfit: req.takeProfit, reduceOnly: false, status: ["NEW", "OPEN", "FILLED", "PARTIALLY_FILLED"] }, "position_open_verified"); if (result.accepted && req.stopLoss) await this.moveStopLoss({ ...ctx, idempotencyKey: `${ctx.idempotencyKey}|sl` }, { symbol, triggerPrice: req.stopLoss, quantity: req.quantity }); if (result.accepted && req.takeProfit) await this.moveTakeProfit({ ...ctx, idempotencyKey: `${ctx.idempotencyKey}|tp` }, { symbol, triggerPrice: req.takeProfit, quantity: req.quantity }); return result; }
  async modifyPosition(ctx: AdapterCommandContext, req: any) { if (req.stopLoss) return this.moveStopLoss(ctx, { symbol: req.symbol, triggerPrice: req.stopLoss, quantity: req.quantity }); if (req.takeProfit) return this.moveTakeProfit(ctx, { symbol: req.symbol, triggerPrice: req.takeProfit, quantity: req.quantity }); return this.execute(ctx, async () => undefined, normalizeSymbol(req.symbol), {}, "position_modify_noop"); }
  async closePosition(ctx: AdapterCommandContext, req: any) { const symbol = normalizeSymbol(req.symbol); const pos = await this.client.getPosition(symbol); const side = pos?.side === "LONG" ? "SELL" : "BUY"; return this.execute(ctx, async () => this.client.placeOrder({ symbol, side, quantity: req.quantity ?? pos?.quantity ?? 0, type: "MARKET", reduceOnly: true, clientOrderId: ctx.idempotencyKey }), symbol, { quantity: 0, reduceOnly: true, status: ["NEW", "OPEN", "FILLED", "PARTIALLY_FILLED"] }, "position_close_verified"); }
  partialClose(ctx: AdapterCommandContext, req: any) { return this.closePosition(ctx, req); }
  moveStopLoss(ctx: AdapterCommandContext, req: any) { const symbol = normalizeSymbol(req.symbol); return this.execute(ctx, async () => this.client.placeOrder({ symbol, side: "SELL", quantity: req.quantity, type: "STOP_MARKET", triggerPrice: req.triggerPrice, reduceOnly: true, protectionKind: "STOP_LOSS", clientOrderId: ctx.idempotencyKey }), symbol, { stopLoss: req.triggerPrice, reduceOnly: true }, "stop_loss_verified"); }
  moveTakeProfit(ctx: AdapterCommandContext, req: any) { const symbol = normalizeSymbol(req.symbol); return this.execute(ctx, async () => this.client.placeOrder({ symbol, side: "SELL", quantity: req.quantity, type: "TAKE_PROFIT_MARKET", triggerPrice: req.triggerPrice, reduceOnly: true, protectionKind: "TAKE_PROFIT", clientOrderId: ctx.idempotencyKey }), symbol, { takeProfit: req.triggerPrice, reduceOnly: true }, "take_profit_verified"); }
  startTrailing(ctx: AdapterCommandContext, req: any) { const symbol = normalizeSymbol(req.symbol); return this.execute(ctx, async () => this.client.placeOrder({ symbol, side: "SELL", quantity: req.quantity, type: "TRAILING_STOP_MARKET", triggerPrice: req.triggerPrice, reduceOnly: true, protectionKind: "TRAILING_STOP", clientOrderId: ctx.idempotencyKey }), symbol, { reduceOnly: true }, "trailing_verified"); }
  cancelOrder(ctx: AdapterCommandContext, req: any) { const symbol = normalizeSymbol(req.symbol); return this.execute(ctx, async () => this.client.cancelOrder(symbol, req.orderId), symbol, { status: ["CANCELED"] }, "order_cancel_verified"); }
  protected async execute(ctx: AdapterCommandContext, op: () => Promise<AdapterOrderSnapshot | undefined>, symbol: string, expected: VerificationExpectation, okReason: string): Promise<AdapterOrderResult> { assertContext(ctx); if (!ctx.commandId || !ctx.idempotencyKey) throw new FatalError("commandId and idempotencyKey are required", "missing_idempotency"); const prev = this.accepted.get(ctx.idempotencyKey); if (prev) return { ...prev, duplicate: true }; try { const order = await op(); const [position, orders, positions] = await Promise.all([this.client.getPosition(symbol), this.client.getOrders(symbol), this.client.getPositions()]); const protection = protectionFromOrders(orders); const verification = verifyExecution(order, position, protection, expected); const res = this.result(ctx, false, order, position, orders, positions, protection, verification.ok ? "VERIFIED" : "FAILED", verification.ok ? [okReason] : verification.reasons); if (res.accepted) this.accepted.set(ctx.idempotencyKey, res); return res; } catch (e) { throw classifyExchangeError(e); } }
  protected result(ctx: AdapterCommandContext, duplicate: boolean, order: AdapterOrderSnapshot | undefined, position: AdapterPositionSnapshot | undefined, orders: AdapterOrderSnapshot[], positions: AdapterPositionSnapshot[], protection: AdapterProtectionSnapshot[], status: VerificationStatus, reasonCodes: string[]): AdapterOrderResult { return { accepted: status !== "FAILED", duplicate, commandId: ctx.commandId, idempotencyKey: ctx.idempotencyKey, exchange: this.exchange, environment: this.account.environment, order, position, orders, positions, protection, verification: { status, reasonCodes, checkedAt: new Date().toISOString(), expected: {}, actual: { order, position, protection } } }; }
}
export type VerificationExpectation = { quantity?: number; entryPrice?: number; stopLoss?: number; takeProfit?: number; reduceOnly?: boolean; status?: string[] };
export function verifyExecution(order: AdapterOrderSnapshot | undefined, position: AdapterPositionSnapshot | undefined, protection: AdapterProtectionSnapshot[], expected: VerificationExpectation) { const reasons: string[] = []; if (!order && expected.status) reasons.push("order_missing"); if (order && expected.status && !expected.status.includes(order.status)) reasons.push("order_status_mismatch"); if (expected.reduceOnly !== undefined && order && order.reduceOnly !== expected.reduceOnly) reasons.push("reduce_only_mismatch"); if (expected.quantity !== undefined) { const actual = position?.quantity ?? 0; if (Math.abs(actual - expected.quantity) > Math.max(1e-8, expected.quantity * 0.001)) reasons.push("position_quantity_mismatch"); } if (expected.entryPrice && position?.entryPrice && Math.abs(position.entryPrice - expected.entryPrice) > expected.entryPrice * 0.005) reasons.push("entry_price_mismatch"); if (expected.stopLoss && !protection.some((p) => p.kind === "STOP_LOSS" && Math.abs((p.triggerPrice ?? 0) - expected.stopLoss!) <= expected.stopLoss! * 0.002)) reasons.push("stop_loss_missing_or_mismatch"); if (expected.takeProfit && !protection.some((p) => p.kind === "TAKE_PROFIT" && Math.abs((p.triggerPrice ?? 0) - expected.takeProfit!) <= expected.takeProfit! * 0.002)) reasons.push("take_profit_missing_or_mismatch"); return { ok: reasons.length === 0, reasons: reasons.length ? reasons : ["verified"] }; }
export function protectionFromOrders(orders: AdapterOrderSnapshot[]): AdapterProtectionSnapshot[] { return orders.filter(o => o.reduceOnly || o.protectionKind || o.triggerPrice !== undefined).map(o => ({ symbol: o.symbol, kind: o.protectionKind ?? (o.type.includes("TAKE") ? "TAKE_PROFIT" : o.type.includes("STOP") ? "STOP_LOSS" : "REDUCE_ONLY"), orderId: o.orderId, side: o.side, quantity: o.quantity, triggerPrice: o.triggerPrice, status: o.status, reduceOnly: o.reduceOnly, raw: o.raw })); }
