import { AdapterAccountContext, AdapterCommandContext, AdapterHealthSnapshot, AdapterOrderResult, AdapterOrderSnapshot, AdapterPositionSnapshot, AdapterProtectionSnapshot, CryptoAdapter, CryptoEnvironment, CryptoExchangeClient, FatalError, VerificationStatus } from "./types";

export function assertContext(ctx: AdapterAccountContext): void { if (!ctx.customerId || !ctx.accountId || !ctx.executorId) throw new FatalError("customerId/accountId/executorId are required", "missing_account_context"); if (!isEnvironment(ctx.environment)) throw new FatalError("explicit crypto environment is required", "invalid_environment"); }
export function isEnvironment(v: unknown): v is CryptoEnvironment { return v === "demo" || v === "testnet" || v === "live"; }
export function classifyExchangeError(error: unknown): FatalError { const msg = error instanceof Error ? error.message : String(error); if (/auth|signature|key/i.test(msg)) return new FatalError(msg, "auth_failure"); if (/symbol/i.test(msg)) return new FatalError(msg, "invalid_symbol"); if (/balance|margin/i.test(msg)) return new FatalError(msg, "insufficient_balance"); if (/reject/i.test(msg)) return new FatalError(msg, "order_rejected"); if (/environment/i.test(msg)) return new FatalError(msg, "invalid_environment"); return new FatalError(msg, "exchange_error"); }

export abstract class BaseCryptoAdapter implements CryptoAdapter {
  protected connected = false; protected readonly accepted = new Map<string, AdapterOrderResult>();
  protected constructor(protected readonly exchange: "binance" | "bybit", protected readonly account: AdapterAccountContext, protected readonly client: CryptoExchangeClient) { assertContext(account); }
  async connect() { await this.client.connect(); this.connected = true; return this.health(); }
  async disconnect() { await this.client.disconnect(); this.connected = false; return this.health(); }
  async health(): Promise<AdapterHealthSnapshot> { return { status: this.connected ? "connected" : "disconnected", exchange: this.exchange, environment: this.account.environment, connected: this.connected, account: this.account, checkedAt: new Date().toISOString(), reasonCodes: this.connected ? [] : ["not_connected"] }; }
  async heartbeat() { const ok = await this.client.ping(); this.connected = ok; return this.health(); }
  async reconnect() { await this.disconnect(); return this.connect(); }
  getPosition(symbol: string) { return this.client.getPosition(symbol); } getOrders(symbol?: string) { return this.client.getOrders(symbol); } getBalance() { return this.client.getBalance(); } getSymbolInfo(symbol: string) { return this.client.getSymbolInfo(symbol); }
  async synchronize() { const [positions, orders] = await Promise.all([this.client.getPositions(), this.client.getOrders()]); return { positions, orders, protection: protectionFromOrders(orders) }; }
  async repair(): Promise<AdapterOrderResult> { const sync = await this.synchronize(); return this.result({ commandId: "repair", idempotencyKey: "repair", ...this.account }, false, undefined, sync.positions[0], sync.orders, sync.positions, sync.protection, "UNKNOWN", ["manual_repair_not_implemented"]); }
  async openPosition(ctx: AdapterCommandContext, req: any) { return this.execute(ctx, async () => this.client.placeOrder({ symbol: req.symbol, side: req.side === "LONG" ? "BUY" : "SELL", quantity: req.quantity, type: req.orderType ?? "MARKET", price: req.price, clientOrderId: ctx.idempotencyKey } ), req.symbol, "position_open_verified", req.quantity); }
  async modifyPosition(ctx: AdapterCommandContext, req: any) { if (req.stopLoss) return this.moveStopLoss(ctx, { symbol: req.symbol, triggerPrice: req.stopLoss, quantity: req.quantity }); if (req.takeProfit) return this.moveTakeProfit(ctx, { symbol: req.symbol, triggerPrice: req.takeProfit, quantity: req.quantity }); return this.execute(ctx, async () => undefined, req.symbol, "position_modify_noop"); }
  async closePosition(ctx: AdapterCommandContext, req: any) { const pos = await this.client.getPosition(req.symbol); const side = pos?.side === "LONG" ? "SELL" : "BUY"; return this.execute(ctx, async () => this.client.placeOrder({ symbol: req.symbol, side, quantity: req.quantity ?? pos?.quantity ?? 0, type: "MARKET", reduceOnly: true, clientOrderId: ctx.idempotencyKey }), req.symbol, "position_close_verified", 0); }
  partialClose(ctx: AdapterCommandContext, req: any) { return this.closePosition(ctx, req); }
  moveStopLoss(ctx: AdapterCommandContext, req: any) { return this.execute(ctx, async () => this.client.placeOrder({ symbol: req.symbol, side: "SELL", quantity: req.quantity, type: "STOP_MARKET", triggerPrice: req.triggerPrice, reduceOnly: true, protectionKind: "STOP_LOSS", clientOrderId: ctx.idempotencyKey }), req.symbol, "stop_loss_verified"); }
  moveTakeProfit(ctx: AdapterCommandContext, req: any) { return this.execute(ctx, async () => this.client.placeOrder({ symbol: req.symbol, side: "SELL", quantity: req.quantity, type: "TAKE_PROFIT_MARKET", triggerPrice: req.triggerPrice, reduceOnly: true, protectionKind: "TAKE_PROFIT", clientOrderId: ctx.idempotencyKey }), req.symbol, "take_profit_verified"); }
  startTrailing(ctx: AdapterCommandContext, req: any) { return this.execute(ctx, async () => this.client.placeOrder({ symbol: req.symbol, side: "SELL", quantity: req.quantity, type: "TRAILING_STOP_MARKET", triggerPrice: req.triggerPrice, reduceOnly: true, protectionKind: "TRAILING_STOP", clientOrderId: ctx.idempotencyKey }), req.symbol, "trailing_verified"); }
  cancelOrder(ctx: AdapterCommandContext, req: any) { return this.execute(ctx, async () => this.client.cancelOrder(req.symbol, req.orderId), req.symbol, "order_cancel_verified"); }
  protected async execute(ctx: AdapterCommandContext, op: () => Promise<AdapterOrderSnapshot | undefined>, symbol: string, okReason: string, expectedQty?: number): Promise<AdapterOrderResult> { assertContext(ctx); if (!ctx.commandId || !ctx.idempotencyKey) throw new FatalError("commandId and idempotencyKey are required", "missing_idempotency"); const prev = this.accepted.get(ctx.idempotencyKey); if (prev) return { ...prev, duplicate: true }; try { const order = await op(); const [position, orders, positions] = await Promise.all([this.client.getPosition(symbol), this.client.getOrders(symbol), this.client.getPositions()]); const protection = protectionFromOrders(orders); const verified = expectedQty === undefined ? (order && ["NEW","OPEN","FILLED","CANCELED"].includes(order.status)) || !!position : (position?.quantity ?? 0) === expectedQty; const res = this.result(ctx, false, order, position, orders, positions, protection, verified ? "VERIFIED" : "FAILED", [verified ? okReason : "post_operation_verification_failed"]); this.accepted.set(ctx.idempotencyKey, res); return res; } catch (e) { throw classifyExchangeError(e); } }
  protected result(ctx: AdapterCommandContext, duplicate: boolean, order: AdapterOrderSnapshot | undefined, position: AdapterPositionSnapshot | undefined, orders: AdapterOrderSnapshot[], positions: AdapterPositionSnapshot[], protection: AdapterProtectionSnapshot[], status: VerificationStatus, reasonCodes: string[]): AdapterOrderResult { return { accepted: status !== "FAILED", duplicate, commandId: ctx.commandId, idempotencyKey: ctx.idempotencyKey, exchange: this.exchange, environment: this.account.environment, order, position, orders, positions, protection, verification: { status, reasonCodes, checkedAt: new Date().toISOString(), actual: { order, position } } }; }
}
export function protectionFromOrders(orders: AdapterOrderSnapshot[]): AdapterProtectionSnapshot[] { return orders.filter(o => o.reduceOnly || o.protectionKind || o.triggerPrice !== undefined).map(o => ({ symbol: o.symbol, kind: o.protectionKind ?? (o.type.includes("TAKE") ? "TAKE_PROFIT" : o.type.includes("STOP") ? "STOP_LOSS" : "REDUCE_ONLY"), orderId: o.orderId, side: o.side, quantity: o.quantity, triggerPrice: o.triggerPrice, status: o.status, reduceOnly: o.reduceOnly, raw: o.raw })); }
