import { createHmac } from "node:crypto";
import { ExchangeRateLimiter, rateLimitError, retryAfterFrom } from "./rate-limiter";
import { normalizeSymbol, roundDownToStep, roundToTick, splitCryptoSymbol } from "./normalization";
import type { AdapterBalance, AdapterOrderSnapshot, AdapterPositionSnapshot, AdapterProtectionSnapshot, AdapterSymbolInfo, CryptoEnvironment, CryptoExchangeClient, OrderSide, OrderStatus, ProtectionKind, PositionSide } from "./types";
import { FatalError, RetryableError } from "./types";
export type ExchangeKind = "binance" | "bybit";
export type ProductType = "spot" | "usdt_futures" | "linear";
export type RestCredentials = { apiKey: string; apiSecret: string };
export type RestClientConfig = { exchange: ExchangeKind; environment: CryptoEnvironment; productType: ProductType; credentials?: RestCredentials; baseUrl?: string; recvWindowMs?: number; rateLimitMs?: number };
const BINANCE_URLS: Record<CryptoEnvironment, Record<ProductType, string>> = { demo: { spot: "https://testnet.binance.vision", usdt_futures: "https://testnet.binancefuture.com", linear: "https://testnet.binancefuture.com" }, testnet: { spot: "https://testnet.binance.vision", usdt_futures: "https://testnet.binancefuture.com", linear: "https://testnet.binancefuture.com" }, live: { spot: "https://api.binance.com", usdt_futures: "https://fapi.binance.com", linear: "https://fapi.binance.com" } };
const BYBIT_URLS: Record<CryptoEnvironment, string> = { demo: "https://api-demo.bybit.com", testnet: "https://api-testnet.bybit.com", live: "https://api.bybit.com" };
export abstract class SignedRestExchangeClient implements CryptoExchangeClient { protected readonly limiter: ExchangeRateLimiter; protected connected = false; protected symbols = new Map<string, AdapterSymbolInfo>(); protected constructor(protected readonly cfg: RestClientConfig) { if (!["demo","testnet","live"].includes(cfg.environment)) throw new FatalError("explicit environment required", "invalid_environment"); this.limiter = new ExchangeRateLimiter(cfg.rateLimitMs ?? 50); }
  abstract exchange: ExchangeKind; abstract connect(): Promise<void>; async disconnect() { this.connected = false; } abstract ping(): Promise<boolean>; abstract getSymbolInfo(symbol: string): Promise<AdapterSymbolInfo>; abstract getBalance(): Promise<AdapterBalance[]>; abstract getPosition(symbol: string): Promise<AdapterPositionSnapshot | undefined>; abstract getPositions(): Promise<AdapterPositionSnapshot[]>; abstract getOrders(symbol?: string): Promise<AdapterOrderSnapshot[]>; abstract placeOrder(order: Record<string, unknown>): Promise<AdapterOrderSnapshot>; abstract cancelOrder(symbol: string, orderId: string): Promise<AdapterOrderSnapshot>;
  protected requireCredentials() { if (!this.cfg.credentials?.apiKey || !this.cfg.credentials.apiSecret) throw new FatalError("authenticated exchange credentials required", "auth_failure"); return this.cfg.credentials; }
  protected async request<T>(method: string, path: string, params: Record<string, unknown> = {}, signed = false): Promise<T> { return this.limiter.schedule(async () => { const { url, init } = this.buildRequest(method, path, params, signed); const res = await fetch(url, init); const text = await res.text(); const body = text ? JSON.parse(text) : {}; if (res.status === 429 || res.status === 418) throw rateLimitError(`${this.exchange}_rate_limited`, retryAfterFrom(res.headers)); if (!res.ok || this.isApiError(body)) throw this.toExchangeError(body, res.status); return body as T; }); }
  protected abstract buildRequest(method: string, path: string, params: Record<string, unknown>, signed: boolean): { url: string; init: RequestInit };
  protected abstract isApiError(body: any): boolean; protected abstract toExchangeError(body: any, status: number): Error;
}
export class BinanceRestClient extends SignedRestExchangeClient { exchange: ExchangeKind = "binance"; private readonly baseUrl: string; constructor(cfg: Omit<RestClientConfig, "exchange">) { super({ ...cfg, exchange: "binance" }); this.baseUrl = cfg.baseUrl ?? BINANCE_URLS[cfg.environment][cfg.productType]; }
  async connect() { if (this.cfg.environment === "live" && this.baseUrl.includes("testnet")) throw new FatalError("live environment cannot use testnet endpoint", "invalid_environment"); await this.ping(); this.connected = true; }
  async ping() { await this.request("GET", this.prefix("/ping")); return true; }
  async getSymbolInfo(symbol: string) { const normalized = normalizeSymbol(symbol); const cached = this.symbols.get(normalized); if (cached) return cached; const body: any = await this.request("GET", this.prefix("/exchangeInfo"), { symbol: normalized }); const raw = (body.symbols ?? [body.symbols?.[0]]).find?.((s: any) => s.symbol === normalized) ?? body.symbols?.[0]; const filters = raw?.filters ?? []; const lot = filters.find((f: any) => f.filterType === "LOT_SIZE" || f.filterType === "MARKET_LOT_SIZE") ?? {}; const price = filters.find((f: any) => f.filterType === "PRICE_FILTER") ?? {}; const notional = filters.find((f: any) => f.filterType === "MIN_NOTIONAL" || f.filterType === "NOTIONAL") ?? {}; const parts = splitCryptoSymbol(normalized); const info = { symbol: normalized, baseAsset: raw?.baseAsset ?? parts.baseAsset, quoteAsset: raw?.quoteAsset ?? parts.quoteAsset, minQuantity: Number(lot.minQty ?? 0), quantityStep: Number(lot.stepSize ?? 0), priceStep: Number(price.tickSize ?? 0), minNotional: Number(notional.minNotional ?? notional.notional ?? 0), raw } as AdapterSymbolInfo; this.symbols.set(normalized, info); return info; }
  async getBalance() { const body: any = await this.request("GET", this.cfg.productType === "spot" ? "/api/v3/account" : "/fapi/v2/balance", {}, true); const rows = Array.isArray(body) ? body : body.balances ?? []; return rows.map((b: any) => ({ asset: b.asset, available: Number(b.availableBalance ?? b.free ?? 0), total: Number(b.balance ?? (Number(b.free ?? 0) + Number(b.locked ?? 0))), raw: b })); }
  async getPosition(symbol: string) { return (await this.getPositions()).find((p: AdapterPositionSnapshot) => p.symbol === normalizeSymbol(symbol)); }
  async getPositions() { if (this.cfg.productType === "spot") return []; const body: any[] = await this.request("GET", "/fapi/v2/positionRisk", {}, true); return body.filter((p: any) => Math.abs(Number(p.positionAmt ?? 0)) > 0).map((p: any) => ({ symbol: p.symbol, side: (Number(p.positionAmt) >= 0 ? "LONG" : "SHORT") as PositionSide, quantity: Math.abs(Number(p.positionAmt)), entryPrice: Number(p.entryPrice), markPrice: Number(p.markPrice), unrealizedPnl: Number(p.unRealizedProfit), liquidationPrice: Number(p.liquidationPrice), raw: p })); }
  async getOrders(symbol?: string) { const params = symbol ? { symbol: normalizeSymbol(symbol) } : {}; const path = this.cfg.productType === "spot" ? "/api/v3/openOrders" : "/fapi/v1/openOrders"; const body: any[] = await this.request("GET", path, params, true); return body.map(mapBinanceOrder); }
  async placeOrder(order: Record<string, unknown>) { const info = await this.getSymbolInfo(String(order.symbol)); const symbol = info.symbol; const quantity = roundDownToStep(Number(order.quantity), info.quantityStep); const price = order.price ? roundToTick(Number(order.price), info.priceStep) : undefined; const triggerPrice = order.triggerPrice ? roundToTick(Number(order.triggerPrice), info.priceStep) : undefined; if (quantity < info.minQuantity) throw new FatalError("quantity_below_exchange_minimum", "exchange_filter_failure"); const params: Record<string, unknown> = { symbol, side: order.side, type: order.type, quantity, newClientOrderId: order.clientOrderId, reduceOnly: order.reduceOnly || undefined, price, stopPrice: triggerPrice, timeInForce: price ? "GTC" : undefined }; const path = this.cfg.productType === "spot" ? "/api/v3/order" : "/fapi/v1/order"; const body: any = await this.request("POST", path, params, true); return mapBinanceOrder({ ...body, symbol, side: order.side, type: order.type, origQty: quantity, executedQty: body.executedQty ?? 0, price, stopPrice: triggerPrice, reduceOnly: order.reduceOnly, protectionKind: order.protectionKind }); }
  async cancelOrder(symbol: string, orderId: string) { const path = this.cfg.productType === "spot" ? "/api/v3/order" : "/fapi/v1/order"; return mapBinanceOrder(await this.request("DELETE", path, { symbol: normalizeSymbol(symbol), orderId }, true)); }
  async setLeverage(symbol: string, leverage: number) { if (this.cfg.productType === "spot") return; await this.request("POST", "/fapi/v1/leverage", { symbol: normalizeSymbol(symbol), leverage }, true); }
  async setMarginMode(symbol: string, marginType: "ISOLATED"|"CROSSED") { if (this.cfg.productType === "spot") return; await this.request("POST", "/fapi/v1/marginType", { symbol: normalizeSymbol(symbol), marginType }, true); }
  private prefix(path: string) { return this.cfg.productType === "spot" ? `/api/v3${path}` : `/fapi/v1${path}`; }
  protected buildRequest(method: string, path: string, params: Record<string, unknown>, signed: boolean) { const p = clean(params); if (signed) { const creds = this.requireCredentials(); p.timestamp = Date.now(); p.recvWindow = this.cfg.recvWindowMs ?? 5000; const query = qs(p); p.signature = createHmac("sha256", creds.apiSecret).update(query).digest("hex"); } const query = qs(p); return { url: `${this.baseUrl}${path}${query ? `?${query}` : ""}`, init: { method, headers: signed ? ({ "X-MBX-APIKEY": this.requireCredentials().apiKey } as Record<string, string>) : ({} as Record<string, string>) } }; }
  protected isApiError(body: any) { return body && typeof body.code === "number" && body.code < 0; } protected toExchangeError(body: any, status: number) { const msg = String(body?.msg ?? `binance_http_${status}`); if (/timestamp|too many|rate/i.test(msg)) return new RetryableError(msg, "binance_retryable"); if (/api-key|signature|auth/i.test(msg)) return new FatalError(msg, "auth_failure"); return new FatalError(msg, "exchange_rejected"); }
}
export class BybitRestClient extends SignedRestExchangeClient { exchange: ExchangeKind = "bybit"; private readonly baseUrl: string; constructor(cfg: Omit<RestClientConfig, "exchange">) { super({ ...cfg, exchange: "bybit" }); this.baseUrl = cfg.baseUrl ?? BYBIT_URLS[cfg.environment]; }
  private category() { return this.cfg.productType === "spot" ? "spot" : "linear"; } async connect() { if (this.cfg.environment === "live" && this.baseUrl.includes("testnet")) throw new FatalError("live environment cannot use testnet endpoint", "invalid_environment"); await this.ping(); this.connected = true; } async ping() { await this.request("GET", "/v5/market/time"); return true; }
  async getSymbolInfo(symbol: string) { const normalized = normalizeSymbol(symbol); const cached = this.symbols.get(normalized); if (cached) return cached; const body: any = await this.request("GET", "/v5/market/instruments-info", { category: this.category(), symbol: normalized }); const raw = body.result?.list?.[0]; const lot = raw?.lotSizeFilter ?? {}; const price = raw?.priceFilter ?? {}; const parts = splitCryptoSymbol(normalized); const info = { symbol: normalized, baseAsset: raw?.baseCoin ?? parts.baseAsset, quoteAsset: raw?.quoteCoin ?? parts.quoteAsset, minQuantity: Number(lot.minOrderQty ?? 0), quantityStep: Number(lot.qtyStep ?? 0), priceStep: Number(price.tickSize ?? 0), minNotional: Number(lot.minNotionalValue ?? 0), raw } as AdapterSymbolInfo; this.symbols.set(normalized, info); return info; }
  async getBalance() { const body: any = await this.request("GET", "/v5/account/wallet-balance", { accountType: this.cfg.productType === "spot" ? "SPOT" : "UNIFIED" }, true); return (body.result?.list?.[0]?.coin ?? []).map((b: any) => ({ asset: b.coin, available: Number(b.availableToWithdraw ?? b.walletBalance ?? 0), total: Number(b.walletBalance ?? 0), raw: b })); }
  async getPosition(symbol: string) { return (await this.getPositions()).find((p: AdapterPositionSnapshot) => p.symbol === normalizeSymbol(symbol)); }
  async getPositions() { if (this.cfg.productType === "spot") return []; const body: any = await this.request("GET", "/v5/position/list", { category: "linear", settleCoin: "USDT" }, true); return (body.result?.list ?? []).filter((p: any) => Number(p.size ?? 0) > 0).map((p: any) => ({ symbol: p.symbol, side: (p.side === "Sell" ? "SHORT" : "LONG") as PositionSide, quantity: Number(p.size), entryPrice: Number(p.avgPrice), markPrice: Number(p.markPrice), unrealizedPnl: Number(p.unrealisedPnl), liquidationPrice: Number(p.liqPrice), raw: p })); }
  async getOrders(symbol?: string) { const body: any = await this.request("GET", "/v5/order/realtime", { category: this.category(), symbol: symbol ? normalizeSymbol(symbol) : undefined }, true); return (body.result?.list ?? []).map(mapBybitOrder); }
  async placeOrder(order: Record<string, unknown>) { const info = await this.getSymbolInfo(String(order.symbol)); const quantity = roundDownToStep(Number(order.quantity), info.quantityStep); const price = order.price ? roundToTick(Number(order.price), info.priceStep) : undefined; const triggerPrice = order.triggerPrice ? roundToTick(Number(order.triggerPrice), info.priceStep) : undefined; if (quantity < info.minQuantity) throw new FatalError("quantity_below_exchange_minimum", "exchange_filter_failure"); const params: Record<string, unknown> = { category: this.category(), symbol: info.symbol, side: order.side === "BUY" ? "Buy" : "Sell", orderType: mapBybitOrderType(String(order.type)), qty: String(quantity), price: price ? String(price) : undefined, triggerPrice: triggerPrice ? String(triggerPrice) : undefined, reduceOnly: Boolean(order.reduceOnly), orderLinkId: order.clientOrderId }; const body: any = await this.request("POST", "/v5/order/create", params, true); return mapBybitOrder({ ...body.result, symbol: info.symbol, side: params.side, orderType: params.orderType, qty: quantity, price, triggerPrice, reduceOnly: params.reduceOnly, orderLinkId: order.clientOrderId, protectionKind: order.protectionKind }); }
  async cancelOrder(symbol: string, orderId: string) { const body: any = await this.request("POST", "/v5/order/cancel", { category: this.category(), symbol: normalizeSymbol(symbol), orderId }, true); return mapBybitOrder({ ...body.result, symbol: normalizeSymbol(symbol), orderStatus: "Cancelled" }); }
  async setLeverage(symbol: string, leverage: number) { await this.request("POST", "/v5/position/set-leverage", { category: "linear", symbol: normalizeSymbol(symbol), buyLeverage: String(leverage), sellLeverage: String(leverage) }, true); }
  async switchPositionMode(mode: 0|3) { await this.request("POST", "/v5/position/switch-mode", { category: "linear", mode }, true); }
  protected buildRequest(method: string, path: string, params: Record<string, unknown>, signed: boolean) { const p = clean(params); const body = method === "GET" ? "" : JSON.stringify(p); const query = method === "GET" ? qs(p) : ""; const headers: Record<string,string> = { "Content-Type": "application/json" }; if (signed) { const creds = this.requireCredentials(); const ts = String(Date.now()); const recv = String(this.cfg.recvWindowMs ?? 5000); const payload = method === "GET" ? query : body; headers["X-BAPI-API-KEY"] = creds.apiKey; headers["X-BAPI-TIMESTAMP"] = ts; headers["X-BAPI-RECV-WINDOW"] = recv; headers["X-BAPI-SIGN"] = createHmac("sha256", creds.apiSecret).update(ts + creds.apiKey + recv + payload).digest("hex"); } return { url: `${this.baseUrl}${path}${query ? `?${query}` : ""}`, init: { method, headers, body: method === "GET" ? undefined : body } }; }
  protected isApiError(body: any) { return body && Number(body.retCode ?? 0) !== 0; } protected toExchangeError(body: any, status: number) { const msg = String(body?.retMsg ?? `bybit_http_${status}`); if (/too many|rate|timeout/i.test(msg)) return new RetryableError(msg, "bybit_retryable"); if (/api key|signature|auth/i.test(msg)) return new FatalError(msg, "auth_failure"); return new FatalError(msg, "exchange_rejected"); }
}
function clean(params: Record<string, unknown>) { return Object.fromEntries(Object.entries(params).filter(([, v]) => v !== undefined && v !== null && v !== "")); } function qs(params: Record<string, unknown>) { return new URLSearchParams(Object.entries(params).map(([k,v]) => [k, String(v)])).toString(); }
function status(s: string): OrderStatus { const u = String(s).toUpperCase(); if (["NEW","OPEN","PARTIALLY_FILLED","FILLED","CANCELED","REJECTED"].includes(u)) return u === "CANCELLED" ? "CANCELED" as OrderStatus : u as OrderStatus; if (u === "PARTIALLYFILLED") return "PARTIALLY_FILLED"; if (u === "CANCELLED") return "CANCELED"; return "UNKNOWN"; }
function mapBinanceOrder(o: any): AdapterOrderSnapshot { return { orderId: String(o.orderId), clientOrderId: o.clientOrderId ?? o.origClientOrderId, symbol: normalizeSymbol(o.symbol), side: String(o.side).toUpperCase() as OrderSide, type: String(o.type), status: status(o.status ?? "NEW"), quantity: Number(o.origQty ?? o.quantity ?? 0), filledQuantity: Number(o.executedQty ?? 0), price: Number(o.price) || undefined, triggerPrice: Number(o.stopPrice) || undefined, reduceOnly: Boolean(o.reduceOnly), protectionKind: o.protectionKind as ProtectionKind | undefined, raw: o }; }
function mapBybitOrderType(t: string) { if (t.includes("LIMIT")) return "Limit"; return "Market"; } function mapBybitOrder(o: any): AdapterOrderSnapshot { return { orderId: String(o.orderId), clientOrderId: o.orderLinkId, symbol: normalizeSymbol(o.symbol), side: o.side === "Sell" ? "SELL" : "BUY", type: String(o.orderType ?? o.type ?? "Market").toUpperCase(), status: status(o.orderStatus ?? o.status ?? "NEW"), quantity: Number(o.qty ?? o.quantity ?? 0), filledQuantity: Number(o.cumExecQty ?? o.filledQuantity ?? 0), price: Number(o.price) || undefined, triggerPrice: Number(o.triggerPrice) || undefined, reduceOnly: Boolean(o.reduceOnly), protectionKind: o.protectionKind as ProtectionKind | undefined, raw: o }; }
export function protectionFromPositionAndOrders(position: AdapterPositionSnapshot | undefined, orders: AdapterOrderSnapshot[]): AdapterProtectionSnapshot[] { return orders.filter((o) => o.reduceOnly || o.protectionKind || o.triggerPrice !== undefined).map((o) => ({ symbol: o.symbol, kind: o.protectionKind ?? (o.type.includes("TAKE") ? "TAKE_PROFIT" : o.type.includes("STOP") ? "STOP_LOSS" : "REDUCE_ONLY"), orderId: o.orderId, side: o.side, quantity: o.quantity, triggerPrice: o.triggerPrice, status: o.status, reduceOnly: o.reduceOnly, raw: { order: o.raw, position: position?.raw } })); }
