export type CryptoEnvironment = "demo" | "testnet" | "live";
export type AdapterStatus = "connected" | "disconnected" | "degraded";
export type VerificationStatus = "VERIFIED" | "PARTIAL" | "FAILED" | "UNKNOWN";
export type OrderSide = "BUY" | "SELL";
export type PositionSide = "LONG" | "SHORT";
export type OrderStatus = "NEW" | "OPEN" | "PARTIALLY_FILLED" | "FILLED" | "CANCELED" | "REJECTED" | "UNKNOWN";
export type ProtectionKind = "STOP_LOSS" | "TAKE_PROFIT" | "TRAILING_STOP" | "REDUCE_ONLY";

export type AdapterAccountContext = Readonly<{ customerId: string; accountId: string; executorId: string; environment: CryptoEnvironment; apiKeyRef?: string; apiSecretRef?: string; apiKey?: string; apiSecret?: string; productType?: "spot" | "usdt_futures" | "linear"; baseUrl?: string }>;
export type AdapterCommandContext = AdapterAccountContext & Readonly<{ commandId: string; idempotencyKey: string }>;
export type AdapterVerificationResult = Readonly<{ status: VerificationStatus; reasonCodes: string[]; checkedAt: string; expected?: Record<string, unknown>; actual?: Record<string, unknown> }>;
export type AdapterOrderSnapshot = Readonly<{ orderId: string; clientOrderId?: string; symbol: string; side: OrderSide; type: string; status: OrderStatus; quantity: number; filledQuantity: number; price?: number; triggerPrice?: number; reduceOnly: boolean; protectionKind?: ProtectionKind; raw?: unknown }>;
export type AdapterPositionSnapshot = Readonly<{ positionId?: string; symbol: string; side: PositionSide; quantity: number; entryPrice?: number; markPrice?: number; unrealizedPnl?: number; liquidationPrice?: number; stopLoss?: AdapterProtectionSnapshot; takeProfit?: AdapterProtectionSnapshot; raw?: unknown }>;
export type AdapterProtectionSnapshot = Readonly<{ symbol: string; kind: ProtectionKind; orderId?: string; side: OrderSide; quantity: number; triggerPrice?: number; status: OrderStatus; reduceOnly: boolean; raw?: unknown }>;
export type AdapterHealthSnapshot = Readonly<{ status: AdapterStatus; exchange: "binance" | "bybit"; environment: CryptoEnvironment; connected: boolean; account: AdapterAccountContext; checkedAt: string; reasonCodes: string[] }>;
export type AdapterOrderResult = Readonly<{ accepted: boolean; duplicate: boolean; commandId: string; idempotencyKey: string; exchange: "binance" | "bybit"; environment: CryptoEnvironment; order?: AdapterOrderSnapshot; position?: AdapterPositionSnapshot; orders: AdapterOrderSnapshot[]; positions: AdapterPositionSnapshot[]; protection: AdapterProtectionSnapshot[]; verification: AdapterVerificationResult }>;
export class ExchangeError extends Error { constructor(message: string, readonly code: string, readonly retryable = false) { super(message); } }
export class RetryableError extends ExchangeError { constructor(message: string, code = "retryable_exchange_error") { super(message, code, true); } }
export class FatalError extends ExchangeError { constructor(message: string, code = "fatal_exchange_error") { super(message, code, false); } }
export type AdapterSymbolInfo = Readonly<{ symbol: string; baseAsset: string; quoteAsset: string; minQuantity: number; quantityStep: number; priceStep: number; minNotional?: number; raw?: unknown }>;
export type AdapterBalance = Readonly<{ asset: string; available: number; total: number; raw?: unknown }>;
export type OpenPositionRequest = Readonly<{ symbol: string; side: PositionSide; quantity: number; orderType?: "MARKET" | "LIMIT"; price?: number; stopLoss?: number; takeProfit?: number }>;
export type ModifyPositionRequest = Readonly<{ symbol: string; quantity?: number; stopLoss?: number; takeProfit?: number }>;
export type ClosePositionRequest = Readonly<{ symbol: string; quantity?: number }>;
export type MoveProtectionRequest = Readonly<{ symbol: string; triggerPrice: number; quantity?: number }>;
export type CancelOrderRequest = Readonly<{ symbol: string; orderId: string }>;
export interface CryptoExchangeClient { connect(): Promise<void>; disconnect(): Promise<void>; ping(): Promise<boolean>; getSymbolInfo(symbol: string): Promise<AdapterSymbolInfo>; getBalance(): Promise<AdapterBalance[]>; getPosition(symbol: string): Promise<AdapterPositionSnapshot | undefined>; getPositions(): Promise<AdapterPositionSnapshot[]>; getOrders(symbol?: string): Promise<AdapterOrderSnapshot[]>; placeOrder(order: Record<string, unknown>): Promise<AdapterOrderSnapshot>; cancelOrder(symbol: string, orderId: string): Promise<AdapterOrderSnapshot>; setLeverage?(symbol: string, leverage: number): Promise<void>; setMarginMode?(symbol: string, marginMode: string): Promise<void>; switchPositionMode?(mode: 0 | 3): Promise<void>; }
export interface CryptoAdapter { connect(): Promise<AdapterHealthSnapshot>; disconnect(): Promise<AdapterHealthSnapshot>; health(): Promise<AdapterHealthSnapshot>; heartbeat(): Promise<AdapterHealthSnapshot>; openPosition(ctx: AdapterCommandContext, req: OpenPositionRequest): Promise<AdapterOrderResult>; modifyPosition(ctx: AdapterCommandContext, req: ModifyPositionRequest): Promise<AdapterOrderResult>; closePosition(ctx: AdapterCommandContext, req: ClosePositionRequest): Promise<AdapterOrderResult>; partialClose(ctx: AdapterCommandContext, req: ClosePositionRequest): Promise<AdapterOrderResult>; moveStopLoss(ctx: AdapterCommandContext, req: MoveProtectionRequest): Promise<AdapterOrderResult>; moveTakeProfit(ctx: AdapterCommandContext, req: MoveProtectionRequest): Promise<AdapterOrderResult>; startTrailing(ctx: AdapterCommandContext, req: MoveProtectionRequest): Promise<AdapterOrderResult>; cancelOrder(ctx: AdapterCommandContext, req: CancelOrderRequest): Promise<AdapterOrderResult>; getPosition(symbol: string): Promise<AdapterPositionSnapshot | undefined>; getOrders(symbol?: string): Promise<AdapterOrderSnapshot[]>; getBalance(): Promise<AdapterBalance[]>; getSymbolInfo(symbol: string): Promise<AdapterSymbolInfo>; reconnect(): Promise<AdapterHealthSnapshot>; synchronize(): Promise<{ positions: AdapterPositionSnapshot[]; orders: AdapterOrderSnapshot[]; protection: AdapterProtectionSnapshot[] }>; repair(): Promise<AdapterOrderResult>; }
