import assert from "node:assert/strict";
import os from "node:os"; import path from "node:path"; import fs from "node:fs";
import { buildIdempotencyKey, DurableCommandQueue, DurableExecutionEventBus, DurableExecutionRepository, DurableJsonStore, ExecutionManager, ExecutionWorker, type CustomerExecutionProfile, type ImmutableSignal } from "../src/execution-core/index";
const temp = () => path.join(fs.mkdtempSync(path.join(os.tmpdir(), "hbv2-")), "store.json");
const makeManager = (file = temp()) => { const repo = new DurableExecutionRepository(new DurableJsonStore(file)); return new ExecutionManager(repo, new DurableCommandQueue(repo, 20, 2), new DurableExecutionEventBus(repo.store)); };
const signal: ImmutableSignal = Object.freeze({ signalId: "sig1", symbol: "BTCUSDT", market: "crypto", direction: "LONG", entryPrice: 100, stopLoss: 90, takeProfit: 120, createdAt: "2026-01-01T00:00:00.000Z", metadata: Object.freeze({ source: "test" }) });
const base = (over: Partial<CustomerExecutionProfile> = {}): CustomerExecutionProfile => ({ customerId: "cust1", package: { packageId: "pkg", active: true, executionMode: "execution", allowedMarkets: ["crypto", "forex"], maxAccounts: 10, subscriptionValid: true }, executors: [{ executorId: "exec1", approvalStatus: "approved", state: "active", accounts: [{ accountId: "acct1", enabled: true, platform: "Binance", mode: "personal", health: "healthy", permissions: { allowedMarkets: ["crypto"], allowedSymbols: ["*"], leverageAllowed: true }, risk: { equityUsd: 10000, riskPerTradePct: 1, maxDailyRiskPct: 5, usedDailyRiskPct: 0, maxOpenTrades: 5, openTrades: 0, maxSameSymbolTrades: 2, sameSymbolOpenTrades: {}, maxSameDirectionTrades: 2, sameDirectionOpenTrades: { LONG: 0, SHORT: 0 }, maxExposureUsd: 100000, currentExposureUsd: 0, maxDrawdownPct: 10, currentDrawdownPct: 0, maxLeverage: 3, dailyLossLock: false, riskAllowed: true } }] }], ...over });
function run(profile: CustomerExecutionProfile, sig = signal) { const m = makeManager(); m.repo.saveProfile(profile); return { report: m.dispatch(sig), m }; }
function one(profile: CustomerExecutionProfile, sig = signal) { return run(profile, sig).report.plans[0]!; }
assert.equal(one(base({ package: { ...base().package, executionMode: "signal_only" } })).reason, "signal_only_customer");
const unapproved = base(); unapproved.executors[0]!.approvalStatus = "pending"; assert.equal(one(unapproved).reason, "executor_not_approved");
const disabled = base(); disabled.executors[0]!.accounts[0]!.enabled = false; assert.equal(one(disabled).reason, "account_disabled");
const paused = base(); paused.executors[0]!.state = "paused"; assert.equal(one(paused).status, "DEFERRED");
const unsupported = base(); unsupported.executors[0]!.accounts[0]!.platform = "MT5"; assert.equal(one(unsupported).reason, "platform_market_not_supported");
const sym = base(); sym.executors[0]!.accounts[0]!.permissions.allowedSymbols = ["ETHUSDT"]; assert.equal(one(sym).reason, "symbol_not_allowed");
const market = base(); market.executors[0]!.accounts[0]!.permissions.allowedMarkets = ["forex"]; assert.equal(one(market).reason, "market_not_allowed");
const daily = base(); daily.executors[0]!.accounts[0]!.risk.usedDailyRiskPct = 5; assert.equal(one(daily).reason, "daily_risk_limit_exceeded");
const maxOpen = base(); maxOpen.executors[0]!.accounts[0]!.risk.openTrades = 5; assert.equal(one(maxOpen).reason, "max_open_trades_exceeded");
assert.equal(one(base()).status, "APPROVED");
const bybit = base(); bybit.executors[0]!.accounts[0]!.platform = "Bybit"; assert.equal(one(bybit).adapterType, "Bybit");
const mt5 = base(); mt5.executors[0]!.accounts[0]!.platform = "MT5"; mt5.executors[0]!.accounts[0]!.permissions.allowedMarkets = ["forex"]; assert.equal(one(mt5, Object.freeze({ ...signal, signalId: "sig2", symbol: "EURUSD", market: "forex" })).adapterType, "MT5");
const m1 = makeManager(); const cmd = one(base()).commands[0]!; assert.equal(m1.queue.enqueue(cmd).enqueued, true); assert.equal(m1.queue.peek()?.commandId, cmd.commandId); assert.equal(m1.queue.dequeue("w1")?.commandId, cmd.commandId); m1.queue.markSent(cmd.commandId); m1.queue.markAcknowledged(cmd.commandId); m1.queue.markCompleted(cmd.commandId); m1.queue.markVerified(cmd.commandId); assert.equal(m1.queue.snapshot()[0]!.status, "verified");
const file = temp(); const dupManager = makeManager(file); dupManager.repo.saveProfile(base()); assert.equal(dupManager.dispatch(signal).approved, 1); assert.equal(makeManager(file).dispatch(signal).plans[0]!.reason, "duplicate_signal_execution_prevented");
assert.equal(buildIdempotencyKey({ signalId: "s", customerId: "c", executorId: "e", accountId: "a", adapterType: "Binance", action: "OpenPosition", purpose: "p" }), buildIdempotencyKey({ signalId: "s", customerId: "c", executorId: "e", accountId: "a", adapterType: "Binance", action: "OpenPosition", purpose: "p" }));
const iso = makeManager(); iso.repo.saveProfile(base({ customerId: "custA" })); iso.repo.saveProfile(base({ customerId: "custB", executors: [{ ...base().executors[0]!, executorId: "execB", accounts: [{ ...base().executors[0]!.accounts[0]!, accountId: "acctB" }] }] })); iso.dispatch(signal); assert.equal(iso.queue.byCustomer("custA").length, 1); assert.equal(iso.queue.byCustomer("custB").length, 1);
const before = JSON.stringify(signal); run(base()); assert.equal(JSON.stringify(signal), before);
// worker crash/restart recovery, retries, dead letter, multi-worker race, large queue
const wm = makeManager(); wm.repo.saveProfile(base()); wm.dispatch(signal); const leased = wm.queue.lease("crashed", 1)[0]!; wm.queue.mark(leased.commandId, "started", { leaseExpiration: new Date(Date.now() - 1).toISOString() }); assert.equal(makeManager((wm.repo.store as any).filePath).recover(), 1);
let calls = 0; const worker = new ExecutionWorker("w-ok", wm.queue, wm.repo, wm.events, { Binance: { execute: async () => { calls++; return { acknowledged: true, verified: true, completed: true }; } } }); assert.equal(await worker.runOnce(), 1); assert.equal(calls, 1); assert.ok(wm.events.replay().some(e=>e.type === "CommandCompleted"));
const fm = makeManager(); fm.repo.saveProfile(base({ customerId: "fail" })); fm.dispatch(Object.freeze({ ...signal, signalId: "fail-sig" })); const bad = new ExecutionWorker("w-bad", fm.queue, fm.repo, fm.events, { Binance: { execute: async () => { throw Object.assign(new Error("network timeout"), { category: "Network" }); } } }); await bad.runOnce(); assert.equal(fm.queue.snapshot()[0]!.status, "retry_scheduled"); fm.queue.scheduleRetry(fm.queue.snapshot()[0]!.commandId, undefined, "auth failed", "Authentication"); assert.equal(fm.repo.store.read().deadLetters.length, 1);
const lm = makeManager(); lm.repo.saveProfile(base({ customerId: "bulk" })); for (let i=0;i<50;i++) lm.dispatch(Object.freeze({ ...signal, signalId: `bulk-${i}` })); const a = lm.queue.lease("w1", 600), b = lm.queue.lease("w2", 600); assert.equal(new Set([...a, ...b].map(c=>c.commandId)).size, 50); assert.equal(lm.telemetry().queueDepth, 0);
console.log("execution-core tests passed");
