#!/usr/bin/env bash
set -euo pipefail
ENV_FILE="${1:-.env.production}"
[[ -f "$ENV_FILE" ]] || { echo "missing $ENV_FILE"; exit 1; }
required=(APP_DOMAIN DASHBOARD_PASSWORD DATABASE_URL REDIS_URL ENGINE_MODE DATA_SOURCE CAPITAL_MODE EXECUTION_MODE ENGINE_PHASE_LOCK SIGNAL_MIN_TIER SIGNAL_ALLOW_A SIGNAL_ALLOW_B SIGNAL_SEND_ENTRY SIGNAL_SEND_RESULT ENABLE_SIGNAL_MODE_OUTPUT TELEGRAM_BOT_TOKEN TELEGRAM_CHAT_ID SIGNAL_ENABLE_CRYPTO SIGNAL_ENABLE_FOREX SIGNAL_FOREX_READINESS_ONLY LIVE_SAFETY_ENABLED KILL_SWITCH_MODE)
for k in "${required[@]}"; do
  if ! rg -n "^${k}=.+" "$ENV_FILE" >/dev/null; then echo "missing_or_empty:$k"; exit 1; fi
done
echo "env_ok:$ENV_FILE"
