import { DurableExecutionEventBus } from "./events"; import { DurableCommandQueue } from "./queue"; import { DurableExecutionRepository } from "./repositories"; import type { ExecutionCommand, FailureCategory } from "./types";
export type ExecutionAdapter = { execute(command: ExecutionCommand): Promise<{ acknowledged?: boolean; verified?: boolean; completed?: boolean; reason?: string }> };
export class ExecutionWorker { private stopping = false; constructor(readonly workerId: string, private readonly queue: DurableCommandQueue, private readonly repo: DurableExecutionRepository, private readonly events: DurableExecutionEventBus, private readonly adapters: Record<string, ExecutionAdapter>) {}
  heartbeat(status: "starting"|"healthy"|"draining"|"stopped" = "healthy", activeCommandIds: string[] = []) { this.repo.saveWorkerState({ workerId: this.workerId, status, lastHeartbeatAt: new Date().toISOString(), activeCommandIds }); }
  async runOnce(batchSize = 10) { this.heartbeat("healthy"); const leased = this.queue.lease(this.workerId, batchSize); for (const c of leased) await this.process(c); return leased.length; }
  async process(command: ExecutionCommand) { this.events.publish("CommandLeased", { commandId: command.commandId, workerId: this.workerId }); this.heartbeat("healthy", [command.commandId]); try { this.queue.mark(command.commandId, "started"); this.events.publish("CommandStarted", { commandId: command.commandId }); this.events.publish("ExecutionStarted", { commandId: command.commandId }); const adapter = this.adapters[command.adapterId] ?? this.adapters[command.adapterType]; if (!adapter) throw Object.assign(new Error("adapter_unavailable"), { category: "Transient" }); this.queue.markSent(command.commandId); this.events.publish("CommandSent", { commandId: command.commandId }); const result = await adapter.execute(command); if (result.acknowledged !== false) { this.queue.markAcknowledged(command.commandId); this.events.publish("CommandAcknowledged", { commandId: command.commandId }); } if (result.verified === false) throw Object.assign(new Error(result.reason ?? "verification_failed"), { category: "VerificationFailed" }); this.queue.markVerified(command.commandId); this.repo.recordVerification({ commandId: command.commandId, checkedAt: new Date().toISOString(), result }); this.events.publish("CommandVerified", { commandId: command.commandId }); this.queue.markCompleted(command.commandId); this.events.publish("CommandCompleted", { commandId: command.commandId }); this.events.publish("ExecutionCompleted", { commandId: command.commandId }); } catch (e: any) { const category: FailureCategory = e.category ?? classifyFailure(e); this.events.publish("CommandFailed", { commandId: command.commandId, category, reason: e.message }); this.queue.scheduleRetry(command.commandId, undefined, e.message, category); this.events.publish("CommandRetried", { commandId: command.commandId, category }); } finally { this.heartbeat(this.stopping ? "draining" : "healthy", []); } }
  shutdown() { this.stopping = true; this.heartbeat("stopped"); }
}
export function classifyFailure(e: any): FailureCategory { const m = String(e?.message ?? e).toLowerCase(); if (m.includes("auth")) return "Authentication"; if (m.includes("rate")) return "RateLimit"; if (m.includes("network") || m.includes("timeout")) return "Network"; if (m.includes("duplicate")) return "Duplicate"; if (m.includes("reject")) return "ExchangeRejected"; if (m.includes("protect")) return "ProtectionFailed"; if (m.includes("verification")) return "VerificationFailed"; return "Transient"; }
